interface CompositionToken {
    sizing?: string;
    height?: string;
    width?: string;
    spacing?: string;
    verticalPadding?: string;
    horizontalPadding?: string;
    paddingTop?: string;
    paddingRight?: string;
    paddingBottom?: string;
    paddingLeft?: string;
    itemSpacing?: string;
    fill?: string;
    backgroundBlur?: string;
    border?: string;
    borderTop?: string;
    borderRight?: string;
    borderBottom?: string;
    borderLeft?: string;
    borderColor?: string;
    borderRadius?: string;
    borderRadiusTopLeft?: string;
    borderRadiusTopRight?: string;
    borderRadiusBottomRight?: string;
    borderRadiusBottomLeft?: string;
    borderWidth?: string;
    borderWidthTop?: string;
    borderWidthRight?: string;
    borderWidthBottom?: string;
    borderWidthLeft?: string;
    boxShadow?: {
        x?: string;
        y?: string;
        blur?: string;
        spread?: string;
        color?: string;
        type?: "dropShadow" | "innerShadow";
    };
    opacity?: string;
    fontFamily?: string;
    fontWeight?: string;
    fontSize?: string;
    lineHeight?: string;
    typography?: {
        fontFamily?: string;
        fontWeight?: string;
        lineHeight?: string;
        fontSize?: string;
        letterSpacing?: string;
        paragraphSpacing?: string;
        paragraphIndent?: string;
        textDecoration?: "none" | "underline" | "line-through";
        textCase?: "none" | "capitalize" | "uppercase" | "lowercase";
    };
    letterSpacing?: string;
    paragraphSpacing?: string;
    textCase?: "none" | "capitalize" | "uppercase" | "lowercase";
    dimension?: string;
    textDecoration?: "none" | "underline" | "line-through";
}
